name: Run Notebook (papermill)


on:
workflow_dispatch:
schedule:
- cron: '0 2 * * *' # daily at 02:00 UTC (edit as needed)


jobs:
run-notebook:
runs-on: ubuntu-latest


steps:
- name: Checkout repo
uses: actions/checkout@v4


- name: Set up Python
uses: actions/setup-python@v4
with:
python-version: '3.10'


- name: Install dependencies
run: |
python -m pip install --upgrade pip
pip install papermill nbformat


- name: Run notebook with papermill
run: |
mkdir -p outputs
papermill notebooks/training_template.ipynb outputs/output-$(date +"%Y%m%d-%H%M").ipynb -p dataset_path "data/dataset.csv" -p task "classification"


- name: Commit outputs
run: |
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"
git add outputs || true
git commit -m "Add notebook outputs" || true
git push || true
